# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('visited', 'Visited'), ('newly added', 'Newly Added')], default='newly added', max_length=120),
        ),
    ]
