# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20161109_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumb',
            old_name='Foodie',
            new_name='foodie',
        ),
        migrations.RenameField(
            model_name='thumb',
            old_name='Restaurant',
            new_name='restaurant',
        ),
    ]
