# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0001_initial'),
        ('restaurants', '0004_auto_20161109_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=144)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('foodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodies.Foodie')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Review')),
            ],
        ),
    ]
