# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodies.Foodie')),
            ],
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodies.Foodie'),
        ),
    ]
